In [4]:
import pandas as pd

In [5]:
data_url= "./uva.txt"

dataframe = pd.read_table(data_url)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  This is separate from the ipykernel package so we can avoid doing imports until


In [6]:
dataframe[:5]

who  Newbie   Age  Gender Household Income Sexual Preference  \
0  id74364       0  54.0    Male           $50-74          Gay male   
1  id84505       0  39.0  Female        Over $100      Heterosexual   
2  id84509       1  49.0  Female           $40-49      Heterosexual   
3  id87028       1  22.0  Female           $40-49      Heterosexual   
4  id76087       0  20.0    Male           $30-39          Bisexual   

      Country Education Attainment Major Occupation Marital Status  \
0     Ontario         Some College         Computer          Other   
1      Sweden         Professional            Other          Other   
2  Washington         Some College       Management          Other   
3     Florida         Some College         Computer        Married   
4  New Jersey         Some College        Education         Single   

  Years on Internet  
0            4-6 yr  
1            1-3 yr  
2        Under 6 mo  
3           6-12 mo  
4            1-3 yr

In [7]:
dataframe.shape

(19583, 11)

In [8]:
dataframe.dtypes

who                      object
Newbie                    int64
Age                     float64
Gender                   object
Household Income         object
Sexual Preference        object
Country                  object
Education Attainment     object
Major Occupation         object
Marital Status           object
Years on Internet        object
dtype: object

In [9]:
dataframe["Marital Status"].unique()

array(['Other', 'Married', 'Single', 'Divorced', 'Widowed', nan,
       'Separated'], dtype=object)

In [10]:
dataframe.pop('who') # dataframe = dataframe.ix[:, 1:]

dataframe.dtypes

Newbie                    int64
Age                     float64
Gender                   object
Household Income         object
Sexual Preference        object
Country                  object
Education Attainment     object
Major Occupation         object
Marital Status           object
Years on Internet        object
dtype: object

In [11]:
dataframe.pop('Country')

dataframe.dtypes

Newbie                    int64
Age                     float64
Gender                   object
Household Income         object
Sexual Preference        object
Education Attainment     object
Major Occupation         object
Marital Status           object
Years on Internet        object
dtype: object

In [12]:
dataframe.pop('Years on Internet')

dataframe.dtypes

Newbie                    int64
Age                     float64
Gender                   object
Household Income         object
Sexual Preference        object
Education Attainment     object
Major Occupation         object
Marital Status           object
dtype: object

In [42]:
dataframe["Gender"] = dataframe["Gender"].astype("category")
dataframe.dtypes

Newbie                     int64
Age                      float64
Gender                  category
Household Income          object
Sexual Preference         object
Education Attainment      object
Major Occupation          object
Marital Status            object
dtype: object

In [43]:
for col in ['Household Income', 'Sexual Preference', 'Education Attainment', \
            'Major Occupation', "Marital Status"]:
    dataframe[col] = dataframe[col].astype('category')
dataframe.dtypes    

Newbie                     int64
Age                      float64
Gender                  category
Household Income        category
Sexual Preference       category
Education Attainment    category
Major Occupation        category
Marital Status          category
dtype: object

In [44]:
dataframe.head()

Newbie   Age  Gender Household Income Sexual Preference  \
0       0  54.0    Male           $50-74          Gay male   
1       0  39.0  Female        Over $100      Heterosexual   
2       1  49.0  Female           $40-49      Heterosexual   
3       1  22.0  Female           $40-49      Heterosexual   
4       0  20.0    Male           $30-39          Bisexual   

  Education Attainment Major Occupation Marital Status  
0         Some College         Computer          Other  
1         Professional            Other          Other  
2         Some College       Management          Other  
3         Some College         Computer        Married  
4         Some College        Education         Single

In [13]:
dataframe_modified = pd.get_dummies(dataframe)
dataframe_modified[:5]

Newbie   Age  Gender_Female  Gender_Male  Household Income_$10-19  \
0       0  54.0              0            1                        0   
1       0  39.0              1            0                        0   
2       1  49.0              1            0                        0   
3       1  22.0              1            0                        0   
4       0  20.0              0            1                        0   

   Household Income_$20-29  Household Income_$30-39  Household Income_$40-49  \
0                        0                        0                        0   
1                        0                        0                        0   
2                        0                        0                        1   
3                        0                        0                        1   
4                        0                        1                        0   

   Household Income_$50-74  Household Income_$75-99  ...  \
0                        1                        0  ...   
1                        0                        0  ...   
2                        0                        0  ...   
3                        0                        0  ...   
4                        0                        0  ...   

   Major Occupation_Education  Major Occupation_Management  \
0                           0                            0   
1                           0                            0   
2                           0                            1   
3                           0                            0   
4                           1                            0   

   Major Occupation_Other  Major Occupation_Professional  \
0                       0                              0   
1                       1                              0   
2                       0                              0   
3                       0                              0   
4                       0                              0   

   Marital Status_Divorced  Marital Status_Married  Marital Status_Other  \
0                        0                       0                     1   
1                        0                       0                     1   
2                        0                       0                     1   
3                        0                       1                     0   
4                        0                       0                     0   

   Marital Status_Separated  Marital Status_Single  Marital Status_Widowed  
0                         0                      0                       0  
1                         0                      0                       0  
2                         0                      0                       0  
3                         0                      0                       0  
4                         0                      1                       0  

[5 rows x 38 columns]

In [14]:
dataframe_modified.shape

(19583, 38)

In [15]:
dataframe_modified.isnull().sum()

Newbie                                 0
Age                                  561
Gender_Female                          0
Gender_Male                            0
Household Income_$10-19                0
Household Income_$20-29                0
Household Income_$30-39                0
Household Income_$40-49                0
Household Income_$50-74                0
Household Income_$75-99                0
Household Income_Over $100             0
Household Income_Under $10             0
Sexual Preference_Bisexual             0
Sexual Preference_Gay male             0
Sexual Preference_Heterosexual         0
Sexual Preference_Lesbian              0
Sexual Preference_Transgender          0
Sexual Preference_na                   0
Education Attainment_College           0
Education Attainment_Doctoral          0
Education Attainment_Grammar           0
Education Attainment_High School       0
Education Attainment_Masters           0
Education Attainment_Other             0
Education Attain

In [18]:
pd.isnull(dataframe_modified['Age'])

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...  
19553    False
19554    False
19555    False
19556    False
19557    False
19558    False
19559    False
19560    False
19561    False
19562    False
19563    False
19564    False
19565     True
19566    False
19567    False
19568    False
19569    False
19570    False
19571    False
19572    False
19573    False
19574    False
19575    False
19576    False
19577    False
19578    False
19579    False
19580    False
19581    False
19582    False
Name: Age, Length: 19583, dtype: bool

In [22]:
dataframe_modified[pd.isnull(dataframe_modified['Age'])].head()

Newbie  Age  Gender_Female  Gender_Male  Household Income_$10-19  \
42        0  NaN              1            0                        0   
98        0  NaN              0            1                        0   
160       0  NaN              0            1                        0   
227       1  NaN              1            0                        0   
278       0  NaN              0            1                        0   

     Household Income_$20-29  Household Income_$30-39  \
42                         0                        0   
98                         0                        0   
160                        0                        0   
227                        0                        0   
278                        0                        0   

     Household Income_$40-49  Household Income_$50-74  \
42                         0                        0   
98                         0                        0   
160                        0                        0   
227                        0                        0   
278                        0                        0   

     Household Income_$75-99  ...  Major Occupation_Education  \
42                         0  ...                           0   
98                         0  ...                           0   
160                        0  ...                           0   
227                        0  ...                           0   
278                        0  ...                           0   

     Major Occupation_Management  Major Occupation_Other  \
42                             0                       0   
98                             1                       0   
160                            0                       0   
227                            0                       1   
278                            0                       0   

     Major Occupation_Professional  Marital Status_Divorced  \
42                               1                        0   
98                               0                        0   
160                              1                        0   
227                              0                        1   
278                              0                        0   

     Marital Status_Married  Marital Status_Other  Marital Status_Separated  \
42                        0                     0                         0   
98                        1                     0                         0   
160                       1                     0                         0   
227                       0                     0                         0   
278                       1                     0                         0   

     Marital Status_Single  Marital Status_Widowed  
42                       1                       0  
98                       0                       0  
160                      0                       0  
227                      0                       0  
278                      0                       0  

[5 rows x 38 columns]

In [61]:
dataframe_modified.loc[pd.isnull(dataframe_modified['Age'])].head()

Newbie  Age  Gender_Female  Gender_Male  Household Income_$10-19  \
42        0  NaN              1            0                        0   
98        0  NaN              0            1                        0   
160       0  NaN              0            1                        0   
227       1  NaN              1            0                        0   
278       0  NaN              0            1                        0   

     Household Income_$20-29  Household Income_$30-39  \
42                         0                        0   
98                         0                        0   
160                        0                        0   
227                        0                        0   
278                        0                        0   

     Household Income_$40-49  Household Income_$50-74  \
42                         0                        0   
98                         0                        0   
160                        0                        0   
227                        0                        0   
278                        0                        0   

     Household Income_$75-99  ...  Major Occupation_Education  \
42                         0  ...                           0   
98                         0  ...                           0   
160                        0  ...                           0   
227                        0  ...                           0   
278                        0  ...                           0   

     Major Occupation_Management  Major Occupation_Other  \
42                             0                       0   
98                             1                       0   
160                            0                       0   
227                            0                       1   
278                            0                       0   

     Major Occupation_Professional  Marital Status_Divorced  \
42                               1                        0   
98                               0                        0   
160                              1                        0   
227                              0                        1   
278                              0                        0   

     Marital Status_Married  Marital Status_Other  Marital Status_Separated  \
42                        0                     0                         0   
98                        1                     0                         0   
160                       1                     0                         0   
227                       0                     0                         0   
278                       1                     0                         0   

     Marital Status_Single  Marital Status_Widowed  
42                       1                       0  
98                       0                       0  
160                      0                       0  
227                      0                       0  
278                      0                       0  

[5 rows x 38 columns]

In [23]:
dataframe_modified.loc[pd.isnull(dataframe_modified['Age']), "Age"]

42      NaN
98      NaN
160     NaN
227     NaN
278     NaN
288     NaN
367     NaN
377     NaN
454     NaN
469     NaN
535     NaN
538     NaN
548     NaN
567     NaN
608     NaN
615     NaN
651     NaN
670     NaN
699     NaN
707     NaN
712     NaN
729     NaN
730     NaN
770     NaN
782     NaN
799     NaN
811     NaN
870     NaN
873     NaN
942     NaN
         ..
18617   NaN
18631   NaN
18640   NaN
18666   NaN
18705   NaN
18761   NaN
18786   NaN
18837   NaN
18840   NaN
18890   NaN
18904   NaN
18968   NaN
18991   NaN
19007   NaN
19035   NaN
19076   NaN
19080   NaN
19093   NaN
19163   NaN
19179   NaN
19217   NaN
19228   NaN
19269   NaN
19352   NaN
19428   NaN
19448   NaN
19456   NaN
19486   NaN
19501   NaN
19565   NaN
Name: Age, Length: 561, dtype: float64

In [25]:
dataframe_modified.loc[pd.isnull(dataframe_modified['Age']), "Age"] = \
                                             dataframe_modified['Age'].mean()

In [26]:
dataframe_modified['Age'][pd.isnull(dataframe_modified['Age'])]

Series([], Name: Age, dtype: float64)

In [27]:
dataframe_modified.head()

Newbie   Age  Gender_Female  Gender_Male  Household Income_$10-19  \
0       0  54.0              0            1                        0   
1       0  39.0              1            0                        0   
2       1  49.0              1            0                        0   
3       1  22.0              1            0                        0   
4       0  20.0              0            1                        0   

   Household Income_$20-29  Household Income_$30-39  Household Income_$40-49  \
0                        0                        0                        0   
1                        0                        0                        0   
2                        0                        0                        1   
3                        0                        0                        1   
4                        0                        1                        0   

   Household Income_$50-74  Household Income_$75-99  ...  \
0                        1                        0  ...   
1                        0                        0  ...   
2                        0                        0  ...   
3                        0                        0  ...   
4                        0                        0  ...   

   Major Occupation_Education  Major Occupation_Management  \
0                           0                            0   
1                           0                            0   
2                           0                            1   
3                           0                            0   
4                           1                            0   

   Major Occupation_Other  Major Occupation_Professional  \
0                       0                              0   
1                       1                              0   
2                       0                              0   
3                       0                              0   
4                       0                              0   

   Marital Status_Divorced  Marital Status_Married  Marital Status_Other  \
0                        0                       0                     1   
1                        0                       0                     1   
2                        0                       0                     1   
3                        0                       1                     0   
4                        0                       0                     0   

   Marital Status_Separated  Marital Status_Single  Marital Status_Widowed  
0                         0                      0                       0  
1                         0                      0                       0  
2                         0                      0                       0  
3                         0                      0                       0  
4                         0                      1                       0  

[5 rows x 38 columns]

In [28]:
dataframe_modified.head()

Newbie   Age  Gender_Female  Gender_Male  Household Income_$10-19  \
0       0  54.0              0            1                        0   
1       0  39.0              1            0                        0   
2       1  49.0              1            0                        0   
3       1  22.0              1            0                        0   
4       0  20.0              0            1                        0   

   Household Income_$20-29  Household Income_$30-39  Household Income_$40-49  \
0                        0                        0                        0   
1                        0                        0                        0   
2                        0                        0                        1   
3                        0                        0                        1   
4                        0                        1                        0   

   Household Income_$50-74  Household Income_$75-99  ...  \
0                        1                        0  ...   
1                        0                        0  ...   
2                        0                        0  ...   
3                        0                        0  ...   
4                        0                        0  ...   

   Major Occupation_Education  Major Occupation_Management  \
0                           0                            0   
1                           0                            0   
2                           0                            1   
3                           0                            0   
4                           1                            0   

   Major Occupation_Other  Major Occupation_Professional  \
0                       0                              0   
1                       1                              0   
2                       0                              0   
3                       0                              0   
4                       0                              0   

   Marital Status_Divorced  Marital Status_Married  Marital Status_Other  \
0                        0                       0                     1   
1                        0                       0                     1   
2                        0                       0                     1   
3                        0                       1                     0   
4                        0                       0                     0   

   Marital Status_Separated  Marital Status_Single  Marital Status_Widowed  
0                         0                      0                       0  
1                         0                      0                       0  
2                         0                      0                       0  
3                         0                      0                       0  
4                         0                      1                       0  

[5 rows x 38 columns]

In [29]:
dataframe_modified.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19583 entries, 0 to 19582
Data columns (total 38 columns):
Newbie                               19583 non-null int64
Age                                  19583 non-null float64
Gender_Female                        19583 non-null uint8
Gender_Male                          19583 non-null uint8
Household Income_$10-19              19583 non-null uint8
Household Income_$20-29              19583 non-null uint8
Household Income_$30-39              19583 non-null uint8
Household Income_$40-49              19583 non-null uint8
Household Income_$50-74              19583 non-null uint8
Household Income_$75-99              19583 non-null uint8
Household Income_Over $100           19583 non-null uint8
Household Income_Under $10           19583 non-null uint8
Sexual Preference_Bisexual           19583 non-null uint8
Sexual Preference_Gay male           19583 non-null uint8
Sexual Preference_Heterosexual       19583 non-null uint8
Sexual Preference_L

In [30]:
dataframe_modified['Age'] = dataframe_modified['Age'].astype('int')
dataframe_modified.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19583 entries, 0 to 19582
Data columns (total 38 columns):
Newbie                               19583 non-null int64
Age                                  19583 non-null int32
Gender_Female                        19583 non-null uint8
Gender_Male                          19583 non-null uint8
Household Income_$10-19              19583 non-null uint8
Household Income_$20-29              19583 non-null uint8
Household Income_$30-39              19583 non-null uint8
Household Income_$40-49              19583 non-null uint8
Household Income_$50-74              19583 non-null uint8
Household Income_$75-99              19583 non-null uint8
Household Income_Over $100           19583 non-null uint8
Household Income_Under $10           19583 non-null uint8
Sexual Preference_Bisexual           19583 non-null uint8
Sexual Preference_Gay male           19583 non-null uint8
Sexual Preference_Heterosexual       19583 non-null uint8
Sexual Preference_Les

In [31]:
dataframe_modified.head()

Newbie  Age  Gender_Female  Gender_Male  Household Income_$10-19  \
0       0   54              0            1                        0   
1       0   39              1            0                        0   
2       1   49              1            0                        0   
3       1   22              1            0                        0   
4       0   20              0            1                        0   

   Household Income_$20-29  Household Income_$30-39  Household Income_$40-49  \
0                        0                        0                        0   
1                        0                        0                        0   
2                        0                        0                        1   
3                        0                        0                        1   
4                        0                        1                        0   

   Household Income_$50-74  Household Income_$75-99  ...  \
0                        1                        0  ...   
1                        0                        0  ...   
2                        0                        0  ...   
3                        0                        0  ...   
4                        0                        0  ...   

   Major Occupation_Education  Major Occupation_Management  \
0                           0                            0   
1                           0                            0   
2                           0                            1   
3                           0                            0   
4                           1                            0   

   Major Occupation_Other  Major Occupation_Professional  \
0                       0                              0   
1                       1                              0   
2                       0                              0   
3                       0                              0   
4                       0                              0   

   Marital Status_Divorced  Marital Status_Married  Marital Status_Other  \
0                        0                       0                     1   
1                        0                       0                     1   
2                        0                       0                     1   
3                        0                       1                     0   
4                        0                       0                     0   

   Marital Status_Separated  Marital Status_Single  Marital Status_Widowed  
0                         0                      0                       0  
1                         0                      0                       0  
2                         0                      0                       0  
3                         0                      0                       0  
4                         0                      1                       0  

[5 rows x 38 columns]

In [32]:
x_data = dataframe_modified.iloc[:, 1:].as_matrix()
y_data = dataframe_modified.iloc[:, 0].as_matrix().reshape(-1, 1)
y_data.shape, x_data.shape

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


((19583, 1), (19583, 37))

In [33]:
from sklearn import preprocessing # Min-Max Standardzation

min_max_scaler = preprocessing.MinMaxScaler()

x_data = min_max_scaler.fit_transform(x_data)
x_data[:5]

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.65333333, 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        ],
       [0.45333333, 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.     

In [38]:
y_data.shape

(19583, 1)

In [39]:
# list(pd.Series(y_data[:, 0]).index)

In [40]:
import numpy as np 

training_idx = np.random.randint(y_data.shape[0], size=int(y_data.shape[0] * 0.8))
test_idx = np.random.randint(y_data.shape[0], size=int(y_data.shape[0] * 0.2))

x_training, x_test = x_data[training_idx,:], x_data[test_idx,:]
y_training, y_test = y_data[training_idx,:], y_data[test_idx,:]

x_training.shape, x_test.shape

((15666, 37), (3916, 37))

In [41]:
from sklearn import linear_model, datasets

logreg = linear_model.LogisticRegression(fit_intercept=True)
logreg.fit(x_training, y_training.flatten())

C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [42]:
logreg.predict(x_test[:10])

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int64)

In [43]:
logreg.predict_proba(x_test[:10])

array([[0.93357746, 0.06642254],
       [0.46322175, 0.53677825],
       [0.61288252, 0.38711748],
       [0.44151113, 0.55848887],
       [0.6310964 , 0.3689036 ],
       [0.55590413, 0.44409587],
       [0.82486374, 0.17513626],
       [0.67392428, 0.32607572],
       [0.56793514, 0.43206486],
       [0.81623984, 0.18376016]])

In [44]:
x_test.shape

(3916, 37)

In [45]:
y_test.shape

(3916, 1)

In [46]:
logreg.predict(x_test) == y_test.flatten()

array([ True,  True,  True, ...,  True,  True, False])

In [47]:
sum(logreg.predict(x_test) == y_test.flatten()) / len(y_test)

0.7676200204290092

In [48]:
logreg.predict_proba(x_test[:10])

array([[0.93357746, 0.06642254],
       [0.46322175, 0.53677825],
       [0.61288252, 0.38711748],
       [0.44151113, 0.55848887],
       [0.6310964 , 0.3689036 ],
       [0.55590413, 0.44409587],
       [0.82486374, 0.17513626],
       [0.67392428, 0.32607572],
       [0.56793514, 0.43206486],
       [0.81623984, 0.18376016]])

In [51]:
logreg.decision_function(x_test[:10])

array([-2.64298749,  0.1473792 , -0.45944507,  0.23503145, -0.53692326,
       -0.22455538, -1.54965389, -0.72598814, -0.27343152, -1.4910768 ])

In [52]:
logreg.predict(x_test[:10])

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int64)