In [1]:
import pandas as pd
import numpy as np

In [2]:
edges = pd.DataFrame(({'source': [0, 1, 2],
'target': [2, 2, 3],
'weight': [3, 4, 5],
'color': ['red', 'blue', 'blue']}))
edges

source  target  weight color
0       0       2       3   red
1       1       2       4  blue
2       2       3       5  blue

In [4]:
edges.dtypes

source     int64
target     int64
weight     int64
color     object
dtype: object

In [5]:
edges.color

0     red
1    blue
2    blue
Name: color, dtype: object

In [6]:
pd.get_dummies(edges)

source  target  weight  color_blue  color_red
0       0       2       3           0          1
1       1       2       4           1          0
2       2       3       5           1          0

In [7]:
pd.get_dummies(edges['color'])

blue  red
0     0    1
1     1    0
2     1    0

In [10]:
weight_dict={3:'M',4:'L',5:'XL'}
edges['weight_sign']=edges['weight'].map(weight_dict)
edges

source  target  weight color weight_sign
0       0       2       3   red           M
1       1       2       4  blue           L
2       2       3       5  blue          XL

In [16]:
weight_sign=pd.get_dummies(edges['weight_sign'])
weight_sign

L  M  XL
0  0  1   0
1  1  0   0
2  0  0   1

In [17]:
pd.concat([edges,weight_sign],axis=1)

source  target  weight color weight_sign  L  M  XL
0       0       2       3   red           M  0  1   0
1       1       2       4  blue           L  1  0   0
2       2       3       5  blue          XL  0  0   1

In [18]:
pd.get_dummies(edges).values

array([[0, 2, 3, 0, 1, 0, 1, 0],
       [1, 2, 4, 1, 0, 1, 0, 0],
       [2, 3, 5, 1, 0, 0, 0, 1]], dtype=int64)

In [20]:
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', \
'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts',\
'Scouts', 'Scouts', 'Scouts'],
'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd',\

'1st', '1st', '2nd', '2nd'],
'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner',\
'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'],
'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}

In [24]:
df = pd.DataFrame(raw_data,columns = ['regiment','company','name','preTestScore','postTestScore'])

In [25]:
df

regiment company      name  preTestScore  postTestScore
0   Nighthawks     1st    Miller             4             25
1   Nighthawks     1st  Jacobson            24             94
2   Nighthawks     2nd       Ali            31             57
3   Nighthawks     2nd    Milner             2             62
4     Dragoons     1st     Cooze             3             70
5     Dragoons     1st     Jacon             4             25
6     Dragoons     2nd    Ryaner            24             94
7     Dragoons     2nd      Sone            31             57
8       Scouts     1st     Sloan             2             62
9       Scouts     1st     Piger             3             70
10      Scouts     2nd     Riani             2             62
11      Scouts     2nd       Ali             3             70

In [26]:
bins =[0,25,50,75,100]
group_names = ['Low','Okay','Good','Great']
categories=pd.cut(df['postTestScore'],bins,labels=group_names)
categories

0       Low
1     Great
2      Good
3      Good
4      Good
5       Low
6     Great
7      Good
8      Good
9      Good
10     Good
11     Good
Name: postTestScore, dtype: category
Categories (4, object): [Low < Okay < Good < Great]

In [27]:
df['categories']=pd.cut(df['postTestScore'],bins,labels=group_names)
pd.value_counts(df['categories'])

Good     8
Great    2
Low      2
Okay     0
Name: categories, dtype: int64

In [28]:
 pd.get_dummies(df)

preTestScore  postTestScore  regiment_Dragoons  regiment_Nighthawks  \
0              4             25                  0                    1   
1             24             94                  0                    1   
2             31             57                  0                    1   
3              2             62                  0                    1   
4              3             70                  1                    0   
5              4             25                  1                    0   
6             24             94                  1                    0   
7             31             57                  1                    0   
8              2             62                  0                    0   
9              3             70                  0                    0   
10             2             62                  0                    0   
11             3             70                  0                    0   

    regiment_Scouts  company_1st  company_2nd  name_Ali  name_Cooze  \
0                 0            1            0         0           0   
1                 0            1            0         0           0   
2                 0            0            1         1           0   
3                 0            0            1         0           0   
4                 0            1            0         0           1   
5                 0            1            0         0           0   
6                 0            0            1         0           0   
7                 0            0            1         0           0   
8                 1            1            0         0           0   
9                 1            1            0         0           0   
10                1            0            1         0           0   
11                1            0            1         1           0   

    name_Jacobson  ...  name_Milner  name_Piger  name_Riani  name_Ryaner  \
0               0  ...            0           0           0            0   
1               1  ...            0           0           0            0   
2               0  ...            0           0           0            0   
3               0  ...            1           0           0            0   
4               0  ...            0           0           0            0   
5               0  ...            0           0           0            0   
6               0  ...            0           0           0            1   
7               0  ...            0           0           0            0   
8               0  ...            0           0           0            0   
9               0  ...            0           1           0            0   
10              0  ...            0           0           1            0   
11              0  ...            0           0           0            0   

    name_Sloan  name_Sone  categories_Low  categories_Okay  categories_Good  \
0            0          0               1                0                0   
1            0          0               0                0                0   
2            0          0               0                0                1   
3            0          0               0                0                1   
4            0          0               0                0                1   
5            0          0               1                0                0   
6            0          0               0                0                0   
7            0          1               0                0                1   
8            1          0               0                0                1   
9            0          0               0                0                1   
10           0          0               0                0                1   
11           0          0               0                0                1   

    categories_Great  
0                  0  
1                  1  
2                 

In [29]:
raw_example = df.as_matrix()
raw_example[:10]

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([['Nighthawks', '1st', 'Miller', 4, 25, 'Low'],
       ['Nighthawks', '1st', 'Jacobson', 24, 94, 'Great'],
       ['Nighthawks', '2nd', 'Ali', 31, 57, 'Good'],
       ['Nighthawks', '2nd', 'Milner', 2, 62, 'Good'],
       ['Dragoons', '1st', 'Cooze', 3, 70, 'Good'],
       ['Dragoons', '1st', 'Jacon', 4, 25, 'Low'],
       ['Dragoons', '2nd', 'Ryaner', 24, 94, 'Great'],
       ['Dragoons', '2nd', 'Sone', 31, 57, 'Good'],
       ['Scouts', '1st', 'Sloan', 2, 62, 'Good'],
       ['Scouts', '1st', 'Piger', 3, 70, 'Good']], dtype=object)

In [30]:
data = raw_example.copy()

In [31]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [32]:
raw_example[:,0]

array(['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons',
       'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts',
       'Scouts'], dtype=object)

In [33]:
le.fit(raw_example[:,0])

LabelEncoder()

In [34]:
le.classes_
le.transform(raw_example[:,0])

array([1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2])

In [35]:
data[:,0]=le.transform(raw_example[:,0])

In [36]:
data[:3]

array([[1, '1st', 'Miller', 4, 25, 'Low'],
       [1, '1st', 'Jacobson', 24, 94, 'Great'],
       [1, '2nd', 'Ali', 31, 57, 'Good']], dtype=object)

In [38]:
label_column = [0,1,2,5]
label_enconder_list = []
for column_index in label_column:
    le = preprocessing.LabelEncoder()
    le.fit(raw_example[:,column_index])
    data[:,column_index] = le.transform(raw_example[:,column_index])
    label_enconder_list.append(le)
del le
data[:3]

array([[1, 0, 4, 4, 25, 2],
       [1, 0, 2, 24, 94, 1],
       [1, 1, 0, 31, 57, 0]], dtype=object)

In [40]:
label_enconder_list[0].transform(raw_example[:10,0])

array([1, 1, 1, 1, 0, 0, 0, 0, 2, 2])

In [43]:
one_hot_enc = preprocessing.OneHotEncoder()
data[:,0].reshape(-1,1)

array([[1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [2],
       [2],
       [2],
       [2]], dtype=object)

In [44]:
one_hot_enc.fit(data[:,0].reshape(-1,1))

C:\Users\user\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True)

In [45]:
one_hot_enc.n_values_

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:77: DeprecationWarning: Function n_values_ is deprecated; The ``n_values_`` attribute was deprecated in version 0.20 and will be removed 0.22.
  warnings.warn(msg, category=DeprecationWarning)


array([3])

In [46]:
one_hot_enc.active_features_

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:77: DeprecationWarning: Function active_features_ is deprecated; The ``active_features_`` attribute was deprecated in version 0.20 and will be removed 0.22.
  warnings.warn(msg, category=DeprecationWarning)


array([0, 1, 2], dtype=int64)

In [47]:
data[:,0].reshape(-1,1)

array([[1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [2],
       [2],
       [2],
       [2]], dtype=object)

In [48]:
onehotlabels = one_hot_enc.transform(data[:,0].reshape(-1,1)).toarray()
onehotlabels

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [49]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],'B':[103.02,107.26,\
110.35,114.23,114.68], 'C':['big','small','big','small','small']})
df


A       B      C
0  14.00  103.02    big
1  90.20  107.26  small
2  90.95  110.35    big
3  96.27  114.23  small
4  91.21  114.68  small

In [50]:
df["A"]

0    14.00
1    90.20
2    90.95
3    96.27
4    91.21
Name: A, dtype: float64

In [51]:
df["A"] - df["A"].min()

0     0.00
1    76.20
2    76.95
3    82.27
4    77.21
Name: A, dtype: float64

In [52]:
(df["A"]-df["A"].min()) / (df["A"].max()-df["A"].min())

0    0.000000
1    0.926219
2    0.935335
3    1.000000
4    0.938495
Name: A, dtype: float64

In [58]:
df["A"]=(df["A"]-df["A"].min()) / (df["A"].max()-df["A"].min())

In [53]:
df["B"].mean(), df["B"].std

(109.90799999999999, <bound method Series.std of 0    103.02
 1    107.26
 2    110.35
 3    114.23
 4    114.68
 Name: B, dtype: float64>)

In [56]:
df["B"] = ( df["B"] - df["B"].mean() ) / (df["B"].std() )
df["B"]

0   -1.405250
1   -0.540230
2    0.090174
3    0.881749
4    0.973556
Name: B, dtype: float64

In [59]:
df

A         B      C
0  0.000000 -1.405250    big
1  0.926219 -0.540230  small
2  0.935335  0.090174    big
3  1.000000  0.881749  small
4  0.938495  0.973556  small

In [66]:
def feture_scaling(df, scaling_strategy="min-max", column=None):
    if column == None:
        column = [column_name for column_name in df.columns]
    for column_name in column:
        if scaling_strategy == "min-max":
            df[column_name] = ( df[column_name] - df[column_name].min() ) /(df[column_name].max() - df[column_name].min())
        elif scaling_strategy == "z-score":
            df[column_name] = ( df[column_name] - df[column_name].mean() ) /(df[column_name].std() )
    return df

In [68]:
df = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],'B':[103.02,107.26,\
110.35,114.23,114.68], 'C':['big','small','big','small','small']})
df

A       B      C
0  14.00  103.02    big
1  90.20  107.26  small
2  90.95  110.35    big
3  96.27  114.23  small
4  91.21  114.68  small

In [70]:
feture_scaling(df,column=["A","B"])

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

In [72]:
df = pd.io.parsers.read_csv(
'https://raw.githubusercontent.com/rasbt/pattern_classification/\
master/data/wine_data.csv',header=None,usecols=[0,1,2])
df.columns=['Class label', 'Alcohol', 'Malic acid']
df.head()


Class label  Alcohol  Malic acid
0            1    14.23        1.71
1            1    13.20        1.78
2            1    13.16        2.36
3            1    14.37        1.95
4            1    13.24        2.59

In [74]:
df = feture_scaling(df,'z-score',column=['Alcohol','Malic acid'])

In [75]:
df

Class label   Alcohol  Malic acid
0              1  1.514341   -0.560668
1              1  0.245597   -0.498009
2              1  0.196325    0.021172
3              1  1.686791   -0.345835
4              1  0.294868    0.227053
5              1  1.477387   -0.515911
6              1  1.711427   -0.417446
7              1  1.304936   -0.166807
8              1  2.253415   -0.623328
9              1  1.058578   -0.882918
10             1  1.354208   -0.157856
11             1  1.378844   -0.766550
12             1  0.923081   -0.542765
13             1  2.154872   -0.542765
14             1  1.699109   -0.417446
15             1  0.775267   -0.471154
16             1  1.600566   -0.372689
17             1  1.021625   -0.685988
18             1  1.465069   -0.668085
19             1  0.787585    0.683574
20             1  1.304936   -0.632279
21             1 -0.086987    1.310170
22             1  0.873810   -0.426398
23             1 -0.185530   -0.659133
24             1  0.615134   -0.471154
25             1  0.060828   -0.256321
26             1  0.479637   -0.506960
27             1  0.368776   -0.551717
28             1  1.070896   -0.390592
29             1  1.255665   -0.587522
..           ...       ...         ...
148            3  0.393412    0.808893
149            3  0.097782    1.399684
150            3  0.615134    0.701476
151            3 -0.259437    0.298664
152            3  0.134736   -0.390592
153            3  0.282551    0.862601
154            3 -0.518113   -0.936626
155            3  0.208643    2.554412
156            3  1.033943    1.596615
157            3 -0.678246    0.620914
158            3  1.649838   -0.587522
159            3  0.590498   -0.596474
160            3 -0.789107    1.337024
161            3  0.849174    0.826796
162            3 -0.185530    0.835747
163            3 -0.050033    0.996872
164            3  0.960035    0.379227
165            3  0.898446    1.811448
166            3  0.553544    1.220657
167            3 -0.222483    0.925261
168            3  0.713677    0.218102
169            3  0.491955    2.026281
170            3 -0.986193    0.620914
171            3 -0.284073    0.048026
172            3  1.428115    0.155442
173            3  0.873810    2.966176
174            3  0.491955    1.408636
175            3  0.331822    1.739837
176            3  0.208643    0.227053
177            3  1.391162    1.578712

[178 rows x 3 columns]

In [76]:
from sklearn import preprocessing
std_scaler = preprocessing.StandardScaler().fit(df[['Alcohol', 'Malic acid']])

In [77]:
df_std = std_scaler.transform(df[['Alcohol', 'Malic acid']])

In [78]:
df_std

array([[ 1.51861254, -0.5622498 ],
       [ 0.24628963, -0.49941338],
       [ 0.19687903,  0.02123125],
       [ 1.69154964, -0.34681064],
       [ 0.29570023,  0.22769377],
       [ 1.48155459, -0.51736664],
       [ 1.71625494, -0.4186237 ],
       [ 1.3086175 , -0.16727801],
       [ 2.25977152, -0.62508622],
       [ 1.0615645 , -0.88540853],
       [ 1.3580281 , -0.15830138],
       [ 1.38273339, -0.76871232],
       [ 0.92568536, -0.54429654],
       [ 2.16095032, -0.54429654],
       [ 1.70390229, -0.4186237 ],
       [ 0.77745356, -0.47248348],
       [ 1.60508109, -0.37374054],
       [ 1.02450655, -0.68792264],
       [ 1.46920194, -0.66996938],
       [ 0.78980621,  0.68550197],
       [ 1.3086175 , -0.63406285],
       [-0.08723191,  1.31386618],
       [ 0.87627476, -0.42760033],
       [-0.18605311, -0.66099274],
       [ 0.61686912, -0.47248348],
       [ 0.06099988, -0.25704433],
       [ 0.48098997, -0.50839001],
       [ 0.36981612, -0.55327317],
       [ 1.07391715,

In [79]:
minmax_scaler = preprocessing.MinMaxScaler().fit(df[['Alcohol','Malic acid']])

In [80]:
minmax_scaler.transform(df[['Alcohol','Malic acid']])

array([[0.84210526, 0.1916996 ],
       [0.57105263, 0.2055336 ],
       [0.56052632, 0.3201581 ],
       [0.87894737, 0.23913043],
       [0.58157895, 0.36561265],
       [0.83421053, 0.20158103],
       [0.88421053, 0.22332016],
       [0.79736842, 0.27865613],
       [1.        , 0.17786561],
       [0.74473684, 0.12055336],
       [0.80789474, 0.28063241],
       [0.81315789, 0.14624506],
       [0.71578947, 0.19565217],
       [0.97894737, 0.19565217],
       [0.88157895, 0.22332016],
       [0.68421053, 0.21146245],
       [0.86052632, 0.23320158],
       [0.73684211, 0.16403162],
       [0.83157895, 0.16798419],
       [0.68684211, 0.46640316],
       [0.79736842, 0.17588933],
       [0.5       , 0.60474308],
       [0.70526316, 0.22134387],
       [0.47894737, 0.16996047],
       [0.65      , 0.21146245],
       [0.53157895, 0.25889328],
       [0.62105263, 0.20355731],
       [0.59736842, 0.19367589],
       [0.74736842, 0.22924901],
       [0.78684211, 0.18577075],
       [0.

In [81]:
df

Class label   Alcohol  Malic acid
0              1  1.514341   -0.560668
1              1  0.245597   -0.498009
2              1  0.196325    0.021172
3              1  1.686791   -0.345835
4              1  0.294868    0.227053
5              1  1.477387   -0.515911
6              1  1.711427   -0.417446
7              1  1.304936   -0.166807
8              1  2.253415   -0.623328
9              1  1.058578   -0.882918
10             1  1.354208   -0.157856
11             1  1.378844   -0.766550
12             1  0.923081   -0.542765
13             1  2.154872   -0.542765
14             1  1.699109   -0.417446
15             1  0.775267   -0.471154
16             1  1.600566   -0.372689
17             1  1.021625   -0.685988
18             1  1.465069   -0.668085
19             1  0.787585    0.683574
20             1  1.304936   -0.632279
21             1 -0.086987    1.310170
22             1  0.873810   -0.426398
23             1 -0.185530   -0.659133
24             1  0.615134   -0.471154
25             1  0.060828   -0.256321
26             1  0.479637   -0.506960
27             1  0.368776   -0.551717
28             1  1.070896   -0.390592
29             1  1.255665   -0.587522
..           ...       ...         ...
148            3  0.393412    0.808893
149            3  0.097782    1.399684
150            3  0.615134    0.701476
151            3 -0.259437    0.298664
152            3  0.134736   -0.390592
153            3  0.282551    0.862601
154            3 -0.518113   -0.936626
155            3  0.208643    2.554412
156            3  1.033943    1.596615
157            3 -0.678246    0.620914
158            3  1.649838   -0.587522
159            3  0.590498   -0.596474
160            3 -0.789107    1.337024
161            3  0.849174    0.826796
162            3 -0.185530    0.835747
163            3 -0.050033    0.996872
164            3  0.960035    0.379227
165            3  0.898446    1.811448
166            3  0.553544    1.220657
167            3 -0.222483    0.925261
168            3  0.713677    0.218102
169            3  0.491955    2.026281
170            3 -0.986193    0.620914
171            3 -0.284073    0.048026
172            3  1.428115    0.155442
173            3  0.873810    2.966176
174            3  0.491955    1.408636
175            3  0.331822    1.739837
176            3  0.208643    0.227053
177            3  1.391162    1.578712

[178 rows x 3 columns]