In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('mammographic_masses.data.txt')

In [3]:
df.head()

5  67  3 5.1 3.1  1
0  4  43  1   1   ?  1
1  5  58  4   5   3  1
2  4  28  1   1   3  0
3  5  74  1   5   ?  1
4  4  65  1   ?   3  0

In [4]:
df.set_axis(['BI-RAID','Age','Shape','Margin','Density','Severity'],axis=1,inplace=True)

In [5]:
df.head()

BI-RAID Age Shape Margin Density  Severity
0       4  43     1      1       ?         1
1       5  58     4      5       3         1
2       4  28     1      1       3         0
3       5  74     1      5       ?         1
4       4  65     1      ?       3         0

In [6]:
df.drop('BI-RAID',axis=1,inplace=True)

In [7]:
x = df.drop('Severity',axis=1)
y = df.Severity

In [8]:
(df=='?').sum()

C:\Users\user\Anaconda3\lib\site-packages\pandas\core\ops.py:1649: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)


Age          5
Shape       31
Margin      48
Density     76
Severity     0
dtype: int64

In [9]:
df[df=='?']=np.NaN

In [10]:
df.isnull().sum()

Age          5
Shape       31
Margin      48
Density     76
Severity     0
dtype: int64

In [11]:
df_dropNaN=df.dropna()

In [12]:
df_dropNaN.isnull().sum()

Age         0
Shape       0
Margin      0
Density     0
Severity    0
dtype: int64

In [13]:
df_dropNaN.head()

Age Shape Margin Density  Severity
1   58     4      5       3         1
2   28     1      1       3         0
7   57     1      5       3         1
9   76     1      4       3         1
10  42     2      1       3         1

In [14]:
df_dropNaN.Age = df_dropNaN.Age.astype('int')

C:\Users\user\Anaconda3\lib\site-packages\pandas\core\generic.py:5096: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value


In [15]:
col_name=['Shape','Margin','Density']
for i in col_name:
    df_dropNaN[i]=df_dropNaN[i].astype('category')

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [16]:
df_dropNaN.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 830 entries, 1 to 959
Data columns (total 5 columns):
Age         830 non-null int32
Shape       830 non-null category
Margin      830 non-null category
Density     830 non-null category
Severity    830 non-null int64
dtypes: category(3), int32(1), int64(1)
memory usage: 19.2 KB


In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df_dropNaN.drop('Severity',axis=1),df_dropNaN.Severity,test_size=0.3)

In [18]:
from sklearn.tree import DecisionTreeClassifier
Dtree = DecisionTreeClassifier()

In [19]:
Dtree.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [20]:
Dtree_prediction = Dtree.predict(x_test)

In [21]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
rfc = RandomForestClassifier(n_estimators=10)

In [24]:
rfc.fit(x_train,y_train)
randomForest_prediction = rfc.predict(x_test)

In [25]:
from sklearn.neighbors import KNeighborsClassifier

In [26]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train)
KNN_prediction=knn.predict(x_test)

In [27]:
from sklearn.svm import SVC
svm = SVC()

In [29]:
svm.fit(x_train,y_train)
svm_prediction = svm.predict(x_test)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [30]:
from sklearn.linear_model import LogisticRegression

In [31]:
log = LogisticRegression()
log.fit(x_train,y_train)
logistic_prediction = log.predict(x_test)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [32]:
from sklearn.metrics import classification_report,confusion_matrix

In [35]:
print('Dtree')
print(confusion_matrix(y_test,Dtree_prediction))
print(classification_report(y_test,Dtree_prediction))
print('Random Forest')
print(confusion_matrix(y_test,randomForest_prediction))
print(classification_report(y_test,randomForest_prediction))
print('KNN')
print(confusion_matrix(y_test,KNN_prediction))
print(classification_report(y_test,KNN_prediction))
print('SVM')
print(confusion_matrix(y_test,svm_prediction))
print(classification_report(y_test,svm_prediction))
print('Logistic Regression')
print(confusion_matrix(y_test,logistic_prediction))
print(classification_report(y_test,logistic_prediction))

Dtree
[[92 28]
 [45 84]]
              precision    recall  f1-score   support

           0       0.67      0.77      0.72       120
           1       0.75      0.65      0.70       129

   micro avg       0.71      0.71      0.71       249
   macro avg       0.71      0.71      0.71       249
weighted avg       0.71      0.71      0.71       249

Random Forest
[[ 93  27]
 [ 27 102]]
              precision    recall  f1-score   support

           0       0.78      0.78      0.78       120
           1       0.79      0.79      0.79       129

   micro avg       0.78      0.78      0.78       249
   macro avg       0.78      0.78      0.78       249
weighted avg       0.78      0.78      0.78       249

KNN
[[ 94  26]
 [ 29 100]]
              precision    recall  f1-score   support

           0       0.76      0.78      0.77       120
           1       0.79      0.78      0.78       129

   micro avg       0.78      0.78      0.78       249
   macro avg       0.78      0.78      